# Generated by Django 3.2.8 on 2021-11-28 15:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveylines',
            name='geom_line',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
        migrations.AlterField(
            model_name='surveypoints',
            name='geom_point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
